### ISSUE TITLE
Version issue

### ISSUE THREAD

**Issue by Satya-Malladi** [JonathanWilbur/pem-ts#17]
In the following commit, there is a major version bump of typescript. So, can you please revert this and publish a major version.
https://github.com/JonathanWilbur/pem-ts/commit/313efcec174fa45d8c77f2728dce6e793b0df915

**Comment by wesleytodd** [comment]
Hey! Just want to jump in her and mention that *any* typescript update should be released as a major version bump for this package. In this case, the change dropped support for older versions of node (node 10 in this case) which means the compiled output from the typescript tooling contains a syntax error in that version.

If anyone needs a quick workaround just pinning to the previous patch version should work.

**Comment by JonathanWilbur** [comment]
Hey guys, I'm so sorry about this. I have just published both version 2.0.3 and 3.0.0. The latter contains the hard break; the former contains all the old versions. Thank you for reporting!
